# Generated by Django 3.1.2 on 2020-10-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('checking_acct_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('checking_balance', models.FloatField()),
                ('status', models.CharField(max_length=6)),
                ('routing_num', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('username', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=36)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=36)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=13)),
                ('email_addr', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('debit_card_num', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expiration', models.CharField(max_length=8)),
                ('CVV', models.CharField(max_length=8)),
                ('pin_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField()),
                ('mgr_username', models.CharField(max_length=25, unique=True)),
                ('mgr_pwd', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('savings_acct_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('savings_balance', models.FloatField()),
                ('status', models.CharField(max_length=6)),
                ('routing_num', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('trans_date', models.DateField()),
                ('trans_type', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('check_path', models.CharField(max_length=25, unique=True)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.savingsaccount')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSavings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.customer')),
                ('savings_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.savingsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerChecking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.checkingaccount')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.checkingaccount')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='CheckingDebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_acct_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.checkingaccount')),
                ('debit_card_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.debitcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.debitcard')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.transactions')),
            ],
        ),
    ]
