<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-08 23:08
=======
# Generated by Django 3.1.2 on 2020-10-07 19:38
>>>>>>> 8ea189131057333e23a9ff6d6f09e003673e9b7e

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import test.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=36)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=13)),
                ('birthday', models.DateField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
            managers=[
                ('objects', test.managers.ClientManager()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Account',
            fields=[
                ('account_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('checking', 'checking'), ('savings', 'savings')], max_length=10)),
=======
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer Internally', 'Transfer Internally')], max_length=25)),
                ('location', models.CharField(max_length=255)),
                ('check_path', models.CharField(max_length=255, unique=True)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
>>>>>>> 8ea189131057333e23a9ff6d6f09e003673e9b7e
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trans_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=25)),
                ('location', models.CharField(choices=[('Online', 'Online'), ('ATM', 'ATM')], max_length=255)),
                ('check_path', models.CharField(max_length=255, unique=True)),
                ('memo', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.account')),
=======
            name='DebitCard',
            fields=[
                ('card_num', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expiration', models.CharField(max_length=5)),
                ('CVV', models.CharField(max_length=3)),
                ('pin', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 8ea189131057333e23a9ff6d6f09e003673e9b7e
            ],
        ),
    ]
