# Generated by Django 3.1.2 on 2020-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20201008_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_path',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
