# Generated by Django 3.1.2 on 2020-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20201009_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
