# Generated by Django 3.1.2 on 2020-10-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20201009_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_num',
            field=models.CharField(default=36896312, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
