# Generated by Django 3.1.2 on 2020-10-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20201028_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.FloatField(default=0.01),
        ),
    ]
