# Generated by Django 3.1.2 on 2020-11-01 07:39

from django.db import migrations, models
import test.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20201101_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=40, validators=[test.validators.validate_names], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=40, validators=[test.validators.validate_names], verbose_name='last name'),
        ),
    ]
