# Generated by Django 3.1.2 on 2020-11-01 08:02

from django.db import migrations, models
import test.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_auto_20201101_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=36, validators=[test.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=2, validators=[test.validators.validate_state]),
        ),
    ]
