# Generated by Django 3.1.2 on 2020-11-01 16:58

from django.db import migrations, models
import test.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_auto_20201101_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[test.validators.validate_zipcode]),
        ),
    ]
