# Generated by Django 3.1.2 on 2020-11-01 17:02

from django.db import migrations, models
import test.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20201101_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(max_length=13, validators=[test.validators.validate_phone_num]),
        ),
    ]
