# Generated by Django 3.1.2 on 2020-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0015_auto_20201101_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
