# Generated by Django 3.1.2 on 2020-11-02 00:45

from django.db import migrations, models
import test.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0016_auto_20201102_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0, validators=[test.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='amount',
            field=models.FloatField(default=0.0, validators=[test.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0, validators=[test.validators.validate_amount]),
        ),
    ]
